version: "3.8"
services:
  #Main service
  application-incuranse-service:
    build: .
    container_name: incuranse_service_application_container
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      postgres-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/insurance_project
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - WAIT_HOSTS=postgres-service:5432
  #DB Postgres service
  postgres-service:
    container_name: postgres_container
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=insurance_project
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -d insurance_project -U sa" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      -p 5432
