spring:
  server:
    port:8080
    url:http://localhost:${port}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/insurance_project
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: none
  sql:
    init:
      mode: always