CREATE TABLE IF NOT EXISTS driver_number_coefficient (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    coefficient_name varchar(100) NOT NULL,
    coefficient_value NUMERIC(3, 2) NOT NULL
)


CREATE TABLE IF NOT EXISTS age
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20)
);


CREATE TABLE IF NOT EXISTS driving_experience
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20)
);


CREATE TABLE IF NOT EXISTS age_experience_coefficient
(
    age_id        BIGINT,
    experience_id BIGINT,
    coefficient   NUMERIC,
    CONSTRAINT fk_age_id
        FOREIGN KEY (age_id) REFERENCES age (id),
    CONSTRAINT fk_experience_id
        FOREIGN KEY (experience_id) REFERENCES driving_experience (id),
    PRIMARY KEY (age_id, experience_id)
);


CREATE TABLE IF NOT EXISTS KBM
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kbm_class       varchar(10) NOT NULL,
    kmb_coefficient NUMERIC     NOT NULL
);


CREATE TABLE IF NOT EXISTS region_coefficients
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year                int           NOT NULL,
    number              varchar(20)   NOT NULL,
    territory           varchar(255)  NOT NULL,
    coefficient_exclude NUMERIC(5, 3) NOT NULL,
    coefficient_include NUMERIC(5, 3) NOT NULL
);
COMMENT ON COLUMN region_coefficients.year IS 'Год установки коэффициента';
COMMENT ON COLUMN region_coefficients.number IS 'Номер по порядку из Приложения №2 к Указанию Банка России от 28 июля 2020 года N 5515-У';
COMMENT ON COLUMN region_coefficients.territory IS 'Территория преимущественного использования транспортного средства';
COMMENT ON COLUMN region_coefficients.coefficient_exclude IS 'Коэффициент КТ для транспортных средств, за исключением Тракторы, самоходные дорожно-строительные';
COMMENT ON COLUMN region_coefficients.coefficient_include IS 'Коэффициент КТ для Тракторы, самоходные дорожно-строительные';


CREATE TABLE IF NOT EXISTS engine_power (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    power varchar(20) NOT NULL,
    coefficient numeric,

    CONSTRAINT PK_ENGINE_POWER PRIMARY KEY (ID),
    CONSTRAINT UQ_POWER_COEFFICIENT UNIQUE (COEFFICIENT)
);