DROP TABLE IF EXISTS region_coefficients CASCADE;

CREATE TABLE IF NOT EXISTS region_coefficients
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year                int           NOT NULL,
    number              varchar(20)   NOT NULL,
    territory           varchar(255)  NOT NULL,
    coefficient_exclude NUMERIC(5, 3) NOT NULL,
    coefficient_include NUMERIC(5, 3) NOT NULL
);
