name: Deploy docker image
on: pull_request
jobs:
  maven_test_source:
    name: Test maven and Build docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Maven Package
        run: |
          echo "GH_REPO: $GH_IP"
          echo ${{ secrets.SERVER_USER }}
          mvn -B test
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 213.189.218.37
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo ${{ secrets.SERVER_IP }} > 23.txt
            cd insurance/backend
            git pull
            mvn -B clean compile package -DskipTests
            docker compose stop
            docker compose build
            docker compose up -d
            yes|docker system prune -a
      - name: Wait Java app start DOWN
        run: sleep 30s
        shell: bash


#on:
#  push:
#    branches:
#      - 'main'

