name: Deploy docker image
on:
  push:
    branches:
      - main
jobs:
  maven_test_source:
    name: Test maven and Build docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Maven Package
        run: |
          mvn -B test
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "start: " > 23.txt
            date >>23.txt
            cd insurance/backend
            git pull
            mvn -B clean compile package -DskipTests
            docker compose stop
            docker compose build
            docker compose up -d
            yes|docker system prune -a
            cd ../..
            echo "done: " >> 23.txt
            date >>23.txt
      - name: Wait Java app start DOWN
        run: sleep 30s
        shell: bash
