name: Deploy docker image

on: pull_request
#on:
#  push:
#    branches:
#      - 'main'

jobs:
  build_docker_image:
    name: Build docker and push
    runs-on: ubuntu-latest
    steps:
      #Build JAR:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
        #- name: Maven Package
        #run: mvn -B clean compile package -DskipTests

      #Build Docker image:
      #- name: Build and tag image
      # run: docker compose build

      #      - name: Docker login
      #        run: docker login ${{ secrets.DOCKER_LOGIN }} -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

      #Publish image:
  #     - name: Publish image
  #        run: docker compose push
  build:
    name: docker compose up
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd insurance/backend
            git pull
            mvn -B clean compile package -DskipTests
            docker compose stop
            docker compose build
            docker compose up -d
            yes|docker system prune -a
            echo "ok" > status.txt
      - name: Wait Java app start
        run: sleep 30s
        shell: bash

