name: Deploy docker image

on: pull_request
#on:
#  push:
#    branches:
#      - 'main'

jobs:
  build_docker:
    name: docker compose up
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Wait Java app start UP
        shell: bash
        run: |
          echo "GH_REPO: $GH_IP"
        env:
          GH_IP: "${{ secrets.SERVER_USER }}"
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: 213.189.218.37
#          username: ${{ secrets.SERVER_USER }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: 22
#          script: |
#            echo ${{ secrets.SERVER_IP }} > 23.txt
#            cd insurance/backend
#            git pull
#            mvn -B clean compile package -DskipTests
#            docker compose stop
#            docker compose build
#            docker compose up -d
#            yes|docker system prune -a
#      - name: Wait Java app start DOWN
#        run: sleep 30s
#        shell: bash
